# Generated by Django 4.0.4 on 2024-08-28 18:54

from django.db import migrations, models
import station.models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_order_alter_route_source_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(null=True, upload_to=station.models.station_image_file_path),
        ),
    ]
