# Generated by Django 4.0.4 on 2024-08-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_station_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
