# Generated by Django 4.0.4 on 2024-08-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_alter_station_latitude_alter_station_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
