# Generated by Django 4.0.4 on 2024-08-29 15:30

from django.db import migrations, models
import station.models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_alter_route_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='image',
            field=models.ImageField(null=True, upload_to=station.models.crew_member_image_file_path),
        ),
    ]
